import './compat-context.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
await import('../src/client/training-preferences.js');const api=globalThis.AWJ_TRAINING_PREFERENCES;
test('legacy saved substitutions survive and current-session swaps take priority',()=>{const state={session:'gym',sessionStartedAt:10,exerciseSubstitutions:{'Chest Press':'Dumbbell Bench Press'},swaps:{}};api.normalize(state);assert.equal(api.selectedExercise(state,{name:'Chest Press'}),'Dumbbell Bench Press');api.choose(state,'Chest Press','Push-ups');assert.equal(api.selectedExercise(state,{name:'Chest Press'}),'Push-ups');assert.equal(api.selectedExercise(state,{name:'Chest Press'},'custom-other'),'Dumbbell Bench Press');assert.equal(state.exerciseSubstitutions['Chest Press'],'Dumbbell Bench Press');const restored=JSON.parse(JSON.stringify(state));api.normalize(restored);assert.equal(api.selectedExercise(restored,{name:'Chest Press'}),'Push-ups');restored.sessionStartedAt=20;api.normalize(restored);assert.equal(restored.sessionSubstitutions,null);assert.equal(api.selectedExercise(restored,{name:'Chest Press'}),'Dumbbell Bench Press');});
test('empty display preferences and favourite lists are compatible with older backups',()=>{const state={};api.normalize(state);assert.equal(state.displayPreferences.expandedDemo,false);assert.deepEqual(state.routineFavourites,[]);assert.equal(api.toggleFavourite(state,'custom-one'),true);assert.equal(api.toggleFavourite(state,'custom-one'),false);assert.deepEqual(state.routineFavourites,[]);});
test('only accepted targets or actually logged prior values become suggestions',()=>{const state={trainingTargets:{Press:{targetWeight:80}},logs:{Press:{previousSets:[{weight:'50',reps:'10'}]}}};assert.equal(api.suggestions(state,'Press',0).weight,'50');state.trainingTargets.Press.acceptedAt='2026-10-08';assert.equal(api.suggestions(state,'Press',0).weight,80);assert.equal(api.suggestions(state,'Unknown',0),null);});
test('workout history records the performed exercise for each set after a mid-exercise swap',async()=>{
  await import('../src/client/training-session.js');const state={session:'gym',sessionStartedAt:1000,completed:{'gym-0':[0,1]},history:[],logs:{'Chest Press':{sets:[{weight:'40',reps:'10'}]},'Push-ups':{sets:[{}, {reps:'12'}]}},exerciseSubstitutions:{},swaps:{}};
  api.recordSet(state,'Chest Press',0,'Chest Press');api.choose(state,'Chest Press','Push-ups');api.recordSet(state,'Chest Press',1,'Push-ups');
  assert.equal(api.performedExercise(state,{name:'Chest Press'},0),'Chest Press');assert.equal(api.performedExercise(state,{name:'Chest Press'},1),'Push-ups');
  const {record}=AWJ_TRAINING_SESSION.completeWorkout(state,{gym:{exercises:[{name:'Chest Press',sets:2,motion:'chestpress',rest:90}]}},{now:3000});
  assert.deepEqual(record.entries.map(x=>[x.exercise,x.weight,x.reps]),[['Chest Press','40','10'],['Push-ups','','12']]);assert.equal(state.sessionSubstitutions,null);
});
