import {compatibilitySource} from './compat-context.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function context(){const stored=new Map(),requests=[],failed=new Set(),partial=new Set();const cache={match:async key=>stored.get(key)?.clone(),put:async(key,response)=>stored.set(key,response)};
 const assets=[{src:'assets/exercises/poster.webp',type:'image',bytes:4},{src:'assets/exercises/movie.mp4',type:'video',bytes:8},{src:'assets/exercises/finish.webp',type:'image',bytes:4}];
 const ctx={location:{protocol:'https:',href:'https://rep.example/'},navigator:{storage:{estimate:async()=>({quota:10000,usage:0})}},caches:{open:async()=>cache},URL,Response,Headers,AbortController,Map,Set,Promise,Error,fetch:async url=>{requests.push(url);const movie=url.endsWith('.mp4'),status=failed.has(url)?503:partial.has(url)?206:200;return new Response(new Uint8Array(movie?8:4),{status,headers:{'Content-Type':movie?'video/mp4':'image/webp',...(status===206?{'Content-Range':'bytes 0-3/8'}:{})}});}};ctx.window=ctx;ctx.AWJ_BUILD_VERSION='test';ctx.AWJ_MEDIA_PLAYER={assets:()=>assets};vm.createContext(ctx);for(const file of ['media-contract.js','workout-media.js'])vm.runInContext(compatibilitySource+"\n"+(readFileSync('src/client/'+file,'utf8')),ctx);return {api:ctx.AWJ_WORKOUT_MEDIA,stored,requests,failed,partial,ctx};}
test('workout downloads include posters + complete videos and repair partial/missing files',async()=>{const {api,stored,requests,failed,partial}=context(),assets=api.assetsFor({exercises:[{},{}]},x=>x);assert.equal(assets.length,3);assert.equal((await api.inspect(assets)).totalBytes,16);assert.equal((await api.inspect(assets)).complete,false);
 failed.add('https://rep.example/assets/exercises/finish.webp');partial.add('https://rep.example/assets/exercises/movie.mp4');const result=await api.download(assets);assert.equal(result.failures.length,2);assert.equal(result.complete,false);assert.equal((await api.inspect(assets)).ready,1);assert.equal(stored.has('https://rep.example/assets/exercises/movie.mp4'),false);
 failed.clear();partial.clear();const before=requests.length;assert.equal((await api.download(assets)).complete,true);assert.equal(requests.length-before,2);assert.equal((await api.inspect(assets)).complete,true);
 stored.set('https://rep.example/assets/exercises/movie.mp4',new Response(new Uint8Array(3),{headers:{'Content-Type':'video/mp4','Content-Length':'3'}}));assert.equal((await api.inspect(assets)).complete,false);assert.equal((await api.download(assets)).complete,true);
});
test('cancelled download remains incomplete without deleting completed files',async()=>{const {api}=context(),control=new AbortController();control.abort();const assets=api.assetsFor({exercises:[{}]},x=>x),result=await api.download(assets,()=>{},{signal:control.signal});assert.equal(result.aborted,true);assert.equal(result.complete,false);});
test('checking a completed download needs no extra space or network transfer',async()=>{const {api,requests,ctx}=context(),assets=api.assetsFor({exercises:[{}]},x=>x);await api.download(assets);const count=requests.length;ctx.navigator.storage.estimate=async()=>({quota:16,usage:16});assert.equal((await api.download(assets)).complete,true);assert.equal(requests.length,count);});
