/* progress screen composition; calculations and persistence stay in domain modules. */
export function createProgressScreen(ui){
  const {enter,heading,route}=ui;
  let historyFilter={query:'',from:'',to:''};
function historyMarkup(){const q=historyFilter.query.toLowerCase(),rows=(state.history||[]).filter(x=>{const day=String(x.date||'').slice(0,10);return (!historyFilter.from||day>=historyFilter.from)&&(!historyFilter.to||day<=historyFilter.to)&&(!q||`${sessions[x.session]?.name||x.activityLabel||x.session} ${(x.entries||[]).map(e=>e.exercise).join(' ')}`.toLowerCase().includes(q));});return `<p>${rows.length} sessions</p>${rows.map(x=>`<article class="history-result"><h3>${esc(sessions[x.session]?.name||x.activityLabel||x.session)}</h3><p>${esc(String(x.date||'').slice(0,10))} · ${Math.round((Number(x.duration)||0)/60)} min · ${Number(x.sets)||0} sets</p><details><summary>Logged exercises</summary>${(x.entries||[]).map(e=>`<p>${esc(e.exercise)} · ${esc(String(e.weight||'—'))} kg · ${esc(String(e.reps||'—'))} reps${e.rpe?` · RPE ${esc(e.rpe)}`:''}</p>`).join('')||'<p>No detailed set records.</p>'}</details></article>`).join('')||'<p>Complete your first workout to see its history here.</p>'}`;}

function progress(){
    enter('insights','insights');const weekly=AWJ_PRODUCT_SUITE.weeklySummary(state,undefined,AWJ_PERFORMANCE_INSIGHTS),model=AWJ_PERFORMANCE_INSIGHTS.analyze(state),lifts=model.strength?.exercises||[],selected=state.progressExercise||lifts[0]?.exercise,exercise=lifts.find(x=>x.exercise===selected),proposals=state.progressionProposals||[];
    app.innerHTML=AWJ_SAFE_DOM.sanitize(`${heading('Progress','Consistency, performance, and your next step.')}<nav class="screen-shortcuts" aria-label="Progress shortcuts"><button data-open-weekly>Weekly report</button><button data-open-history>Workout history</button></nav><section class="progress-overview"><h2>Am I following my plan?</h2><p class="metric-value">${weekly.completed} / ${weekly.planned}</p><p>Planned sessions completed this week${weekly.totalWorkouts>weekly.completed?` · ${weekly.totalWorkouts-weekly.completed} additional activities`:''}</p></section><section class="exercise-progress"><h2>Am I improving?</h2>${lifts.length?`<label>Exercise<select data-progress-exercise>${lifts.map(x=>`<option ${x.exercise===selected?'selected':''}>${esc(x.exercise)}</option>`).join('')}</select></label><p>${esc(exercise?.recommendation||'Establishing a baseline')} · ${exercise?.sessionCount||0} logged sessions</p>${exercise?.currentE1rm?`<p>Best estimated 1RM: ${esc(String(exercise.currentE1rm))} kg</p><p>${exercise.change28d===null?'More sessions are needed for a 28-day comparison.':`${exercise.change28d>0?'+':''}${exercise.change28d}% over 28 days`}</p>`:''}`:'<p>Log weight and reps across several sessions to see a reliable exercise trend.</p>'}</section><section class="next-step"><h2>What should I do next?</h2><p>${esc(weekly.nextAction)}</p><button class="primary-action" data-progress-train>Open routines</button>${proposals.length?`<details><summary>Next-session targets</summary>${window.AWJ_ENHANCEMENTS_UI.progressionCard(proposals)}</details>`:''}</section><section class="progress-history"><h2>Workout history</h2><label>Search sessions or exercises<input type="search" data-history-search value="${esc(historyFilter.query)}"></label><div class="history-dates"><label>From<input type="date" data-history-from value="${historyFilter.from}"></label><label>To<input type="date" data-history-to value="${historyFilter.to}"></label></div><div data-history-results>${historyMarkup()}</div></section><details class="supporting-details progress-analysis"><summary>Weekly report and detailed analysis</summary><div class="trends-grid"></div>${window.AWJ_PRODUCT_UI.weeklyCard()}${window.AWJ_PRODUCT_UI.experimentsCard()}${window.AWJ_HEALTH_UI.trendMarkup()}</details>`);
    app.querySelector('[data-open-weekly]').onclick=()=>{app.querySelector('.progress-analysis').open=true;const report=app.querySelector('[data-product-weekly]');report.scrollIntoView({block:'start',behavior:'instant'});const title=report.querySelector('h2');title.tabIndex=-1;title.focus({preventScroll:true});};app.querySelector('[data-open-history]').onclick=()=>{app.querySelector('.progress-history').scrollIntoView({block:'start',behavior:'instant'});app.querySelector('[data-history-search]').focus({preventScroll:true});};
    document.querySelector('[data-progress-train]').onclick=()=>route('training-program');document.querySelector('[data-accept-progression]')?.addEventListener('click',()=>{window.AWJ_ENHANCEMENTS_UI.acceptProgression(proposals);progress();});document.querySelector('[data-progress-exercise]')?.addEventListener('change',e=>{state.progressExercise=e.target.value;progress();});for(const [selector,key] of [['[data-history-search]','query'],['[data-history-from]','from'],['[data-history-to]','to']])document.querySelector(selector).addEventListener(key==='query'?'input':'change',e=>{historyFilter[key]=e.target.value;document.querySelector('[data-history-results]').innerHTML=AWJ_SAFE_DOM.sanitize(historyMarkup());});window.AWJ_PRODUCT_UI.bindWeekly(app.querySelector('[data-product-weekly]'));window.AWJ_PRODUCT_UI.bindExperiments(app.querySelector('[data-product-experiments]'));window.AWJ_PERFORMANCE_UI.mount();window.AWJ_HEALTH_UI.bind();
  }
  return {progress};
}
