/* training screen composition; calculations and persistence stay in domain modules. */
export function createTrainingScreen(ui){
  const {enter,heading,route,preferences,sheet}=ui;
  let library={query:'',equipment:'all',muscle:'all'};
function routineCard(id,s){const favourite=state.routineFavourites.includes(id),resume=AWJ_TRAINING_SESSION.isResumableWorkout(state,sessions,id);return `<article class="routine-card" data-routine-card="${esc(id)}"><div><h2>${esc(s.name)}</h2><p>${s.exercises.length} exercises${s.duration?` · ${esc(s.duration)}`:''}</p></div><button data-routine-favourite="${esc(id)}" aria-pressed="${favourite}" aria-label="${favourite?'Unfavourite':'Favourite'} ${esc(s.name)}">${favourite?'★':'☆'}</button><div class="routine-actions"><button class="primary-action" data-session="${esc(id)}">${resume?'Resume':'Preview'}</button>${id.startsWith('custom-')?`<button data-edit-custom="${esc(id)}">Edit</button>`:''}</div></article>`;}

function train(){
    enter('home','train');state.trainingView='program';window.AWJ_CUSTOM_WORKOUTS.getCustomRoutines();
    const ids=Object.keys(sessions).filter(id=>!['bad','gymLite'].includes(id)).sort((a,b)=>Number(state.routineFavourites.includes(b))-Number(state.routineFavourites.includes(a)));
    app.innerHTML=AWJ_SAFE_DOM.sanitize(`${heading('Train','Your routines, this week, and exercise technique.')}<nav class="screen-shortcuts" aria-label="Training shortcuts"><button data-train-jump="routines">Routines</button><button data-train-jump="library">Find exercise</button><button data-train-jump="schedule">Schedule</button></nav><section class="train-week"><h2>This week</h2><div class="week-plan">${window.AWJ_ENHANCEMENTS_UI.dayNames.map(day=>{const focus=window.AWJ_ENHANCEMENTS_UI.daySchedule(day)?.focus||state.preferences?.schedule?.[day]?.focus||'rest';return `<div><span>${esc(day.slice(0,3))}</span><strong>${esc(window.AWJ_ENHANCEMENTS_UI.focusLabel(focus))}</strong></div>`;}).join('')}</div><button data-train-schedule>Edit schedule</button></section><div class="section-title"><h2>Workout routines</h2><button class="primary-action" data-create-new-routine>New routine</button></div><section class="routine-list">${ids.map(id=>routineCard(id,sessions[id])).join('')}</section><section class="exercise-library"><h2>Exercise library</h2><label>Search exercises<input type="search" data-library-search value="${esc(library.query)}" placeholder="Exercise or muscle"></label><div class="library-filters"><label>Equipment<select data-library-equipment>${['all','machines','dumbbells','barbell','bands','bodyweight','cardio'].map(x=>`<option value="${x}" ${library.equipment===x?'selected':''}>${x==='all'?'All equipment':x}</option>`).join('')}</select></label><label>Muscle<select data-library-muscle><option value="all">All muscles</option>${[...new Set(AWJ_EXERCISES.list().flatMap(x=>x.muscleTags))].sort().map(x=>`<option ${library.muscle===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div><p data-library-count role="status"></p><div data-library-results></div></section><details class="supporting-details"><summary>Plan tools and safety</summary><button data-train-review>Technique review</button><button data-train-planreview>Program checkpoint</button><button data-train-export>Export / share plan</button></details>`);
    app.querySelectorAll('[data-train-jump]').forEach(button=>button.onclick=()=>{const target=app.querySelector({routines:'.routine-list',library:'.exercise-library',schedule:'.train-week'}[button.dataset.trainJump]);target?.scrollIntoView({block:'start',behavior:'instant'});if(button.dataset.trainJump==='library')target.querySelector('input')?.focus({preventScroll:true});});
    document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>showSessionPreview(b.dataset.session));document.querySelectorAll('[data-routine-favourite]').forEach(b=>b.onclick=()=>{preferences.toggleFavourite(state,b.dataset.routineFavourite);persist();train();});document.querySelectorAll('[data-edit-custom]').forEach(b=>b.onclick=()=>window.AWJ_CUSTOM_WORKOUTS.openRoutineBuilderModal(b.dataset.editCustom));
    document.querySelector('[data-create-new-routine]').onclick=()=>window.AWJ_CUSTOM_WORKOUTS.openRoutineBuilderModal();document.querySelector('[data-train-schedule]').onclick=()=>route('settings-schedule');document.querySelector('[data-train-review]').onclick=renderReview;document.querySelector('[data-train-planreview]').onclick=renderProgramReview;document.querySelector('[data-train-export]').onclick=()=>{sheet('Plan tools','<button data-plan-export>Export plan</button>',(root)=>root.querySelector('[data-plan-export]').onclick=exportData);};
    for(const [selector,key] of [['[data-library-search]','query'],['[data-library-equipment]','equipment'],['[data-library-muscle]','muscle']])document.querySelector(selector).addEventListener(key==='query'?'input':'change',e=>{library[key]=e.target.value;renderLibrary();});renderLibrary();
  }

function renderLibrary(){const query=library.query.toLowerCase().trim(),rows=AWJ_EXERCISES.list().filter(x=>(!query||`${x.name} ${x.targetMuscles||''}`.toLowerCase().includes(query))&&(library.equipment==='all'||x.equipmentTags.includes(library.equipment))&&(library.muscle==='all'||x.muscleTags.includes(library.muscle)));const results=document.querySelector('[data-library-results]');if(!results)return;document.querySelector('[data-library-count]').textContent=`${rows.length} exercises`;results.innerHTML=AWJ_SAFE_DOM.sanitize(rows.map(x=>`<button class="library-row" data-library-exercise="${esc(x.name)}"><strong>${esc(x.name)}</strong><span>${esc(x.targetMuscles||x.category||'General movement')}</span></button>`).join('')||'<p>No matching exercise. Change your search or filters.</p>');results.querySelectorAll('[data-library-exercise]').forEach(b=>b.onclick=()=>exerciseDetails(b.dataset.libraryExercise));}

function exerciseDetails(name){const item=AWJ_EXERCISES.get(name);sheet(name,`<div class="library-demo">${AWJ_MEDIA_PLAYER.markup(item,{preview:true,context:'library'})}</div><p>${esc(item.setup)}</p><p>${esc(item.execution)}</p><p><strong>Key cue:</strong> ${esc(item.cues)}</p><p><strong>Avoid:</strong> ${esc(item.avoid)}</p>`,()=>AWJ_MEDIA_PLAYER.mount());}
  return {train};
}
